config/routes.rb
SampleApp::Application.routes.draw do  
 
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      post :fb_signin
    end
  end
  
  resources :users do
    member do
      post :fb_unlink
      get :following, :followers       #makes users/1/following and following_user_path
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end
  
  resources :microposts, :only => [:create, :destroy] 
  resources :relationships, :only => [:create, :destroy]
  resources :fb_connections, :only => [:create, :destroy]

  root :to => "pages#home" 
  match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'   
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
	   <h2> 
			<%= pluralize(object.errors.count, "error")%>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase%> from being saved:
		  
		</h2>
		
		<p> There were problems with the following fields: </p>
		 <ul>
		<% object.errors.full_messages.each do |message|%>
		   	<li> <%= message %></li> 
		<% end%>
		</ul> 
	</div>  
	
	
<% end %>

app/views/shared/_fb.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '179989805389930', // App ID
      channelUrl : '//localhost:3000/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar"> <%= link_to gravatar_for(feed_item.user), feed_item.user %></td>  
  <td class="micropost">
	 <span class="user"> 
		<%= link_to feed_item.user.name, feed_item.user%>
	 </span>     
	 <span class="content"> 
		<%= feed_item.content %>
	 </span>
	 <span class="timestamp"> 
	    Post<%= time_ago_in_words(feed_item.created_at)%>  ago.
	 </span>
  </td>      
  <% user = feed_item.user rescue User.find(micropost.user_id)%>         
 <% if user == current_user%>  
	   <td class="delete">
		<%= link_to "delete", feed_item, :method => :delete,
										 :confirm => "Are you sure?", 
										 :title => feed_item.content %>
	   </td>
           
  <% end %>   

</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
 <%= render 'shared/error_messages', :object => f.object %>    
 <div class="fields"> 
	 <%= f.text_area :content %>
 </div>    
<div class="actions">
	<%= f.submit "Submit"%>
</div>
	
<% end %>

app/views/shared/_shared_feed.html.erb
<% if @feed_items.any? %>

<table class="microposts" summary="Status feed">
	<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
</table>                  
   <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_sidebar_shared.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
	   <%= gravatar_for current_user, :size => 30 %>
	<span class="user_name">
		<%= current_user.name%>
	</span>                    
	<span class="microposts">
		<%= pluralize(current_user.microposts.count, "micropost")%>
	</span>
	</a>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
	 <table summary="User stats"> 
		     <tr>
			     <td>
				<a href="<%= following_user_path(@user) %>" >
					<span id="following" class="stat">
						 <%= @user.following.count + @user.fb_friends.count %> following
					</span>
                </a>
				</td> 
				<td>
				<a href="<%= followers_user_path(@user) %>" >
					<span id="followers" class="stat">
						 <%= pluralize(@user.followers.count + @user.fb_friends.count,"followers") %>
					</span>
                 </a>
				</td>
			 </tr>
	  </table>
	
</div>