config/routes.rb
SampleApp::Application.routes.draw do  
 
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      post :fb_signin
    end
  end
  
  resources :users do
    member do
      post :fb_unlink
      get :following, :followers       #makes users/1/following and following_user_path
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end
  
  resources :microposts, :only => [:create, :destroy] 
  resources :relationships, :only => [:create, :destroy]
  resources :fb_connections, :only => [:create, :destroy]

  root :to => "pages#home" 
  match '/signup', :to => 'users#new'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'   
  match '/help', :to => 'pages#help'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy' 

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
	   <ul>
		   <li><%= link_to "About", about_path %></li>    
			<li><%= link_to "Contact", contact_path %></li> 
			<li><%= link_to "News", '#'%></li> 
			<li><%= link_to "Rails Tutorial", 'http://railstutorial.com
			'%></li> 
		</ul>
	</nav>
</footer> 
	   

app/views/layouts/_header.html.erb
      <header>
	  <%= link_to logo, root_path %>  
	  	<nav class="round">
	    	<ul>
				<li><%= link_to "Home", root_path %></li>  
				 
				<% if signed_in?  %>
					<li><%= link_to "Profile", user_path(current_user) %></li> 
					<li><%= link_to "Users", users_path %></li> 
					<li><%= link_to "Settings", edit_user_path(current_user) %></li>  
				<%end%>

              <% if signed_in? and current_user.admin %>
                     <li><%= link_to "Admin", "#"%></li>
               <% end %>
				
				
				<li><%= link_to "Help", help_path %></li>  
				<% if signed_in?  %>
				<li><%= link_to "Sign out", signout_path %></li>  
				<% else%>
				<li><%= link_to "Sign in", signin_path %>
				<%= link_to facebook_logo, "#", {:onclick => "Fb_Login();"} %>  </li>          
				<% end%>
			</ul>
		</nav>
	</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"/>
<![endif]-->
          
    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%> 
<%= stylesheet_link_tag 'blueprint/print', :media => 'print'%>   
<%= stylesheet_link_tag 'jquery.pathSelector-all'%>
<%= stylesheet_link_tag 'bootstrap.min'%>
<%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/smoothness/jquery-ui.css' %>


<!--[if lt IE 9]>
<%= stylesheet_link_tag 'blueprint/ie'%>
<![endif]-->                            

<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Social Scores API | Friend based, social scoreboards for your apps.</title>
	<%= csrf_meta_tag %>  
	<%= render 'layouts/stylesheets'  %>  
	<%= javascript_include_tag :defaults %>
  <%= javascript_include_tag 'bootstrap.min.js' %>
	<%= javascript_include_tag 'facebook.js'%>
</head>
	
<body>    
	<div class = "container">
	          
         <%= render 'layouts/header'  %>  
		<section class="round">  
			<% flash.each do |key,value|%>
			 	<div class="flash <%= key %>">
				    <%= value %>
				</div>  
			<%end%>
			<%= yield %> 
		</section> 
		
		<%= render 'layouts/footer'  %> 
		<%= debug(params) if Rails.env.development? %>
		  
	</div>
</body>
</html>